services:
  postgresql:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: *****
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d workshop"]
      interval: 10s
      timeout: 5s
      retries: 5

  book-rest:
    build:
      context: ./spring-boot-rest-api
      dockerfile: ./Dockerfile
    container_name: book_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
